version: '3.8'

services:
  calculator:
    build: .
    ports:
      - "3000:3000"
    container_name: calculator-container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: always
